
### 新增用户
POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "KimZing",
  "age": 18,
  "balance": 9999,
  "birth": "1992-08-05 12:12",
  "gender": "MAN"
}

### 更新用户

PUT http://localhost:8080/user
Content-Type: application/json

{
  "id": "1",
  "name": "update",
  "age": 19,
  "balance": 99999,
  "birth": "2000-08-05 12:12",
  "version": 0
}

### 删除用户-软删除

DELETE http://localhost:8080/user/1

### 根据ID查询用户

GET http://localhost:8080/user/1

### 根据条件分查询用户

POST http://localhost:8080/user/list?current=1&size=4
Content-Type: application/json

{
  "age": 4
}

### 分页查询用户-XML

GET http://localhost:8080/user/xml?current=1&size=2

### 分页查询用户-Annotation

GET http://localhost:8080/user/annotation?current=2&size=2

### 条件查询-Wrapper,/*小于十岁*/

POST http://localhost:8080/user/wrapper?current=1&size=5
Content-Type: application/json

{
  "name": "u",
  "gender": "WOMAN",
  "age": 10
}

###